### ISSUE TITLE
Mention the continuation project

### ISSUE THREAD

**Issue by ddelange** [dochne/wappalyzer#1]
Would it make sense to mention the continuation project, https://github.com/enthec/webappanalyzer, in the repo description dialog? So you don't need to add a commit :)

**Comment by dochne** [comment]
Super delayed, but fair shout - added it to the top of the readme

**Comment by ddelange** [comment]
glad you still saw it:) cheers

**Comment by roksui** [comment]
@dochne Do you know why the continuation repo doesn't have any js files?

**Comment by ddelange** [comment]
You can also go with https://github.com/HTTPArchive/wappalyzer/issues/52
